---
- name: Rollout TLS certificates
  become: true
  when:
    - certificates | length > 0
  block:

    - name: Provide TLS certificates from Vault
      copy:
        content: >-
          {{ lookup('hashi_vault',
          'secret={{ vault_path.rstrip("/") }}/{{ item }}
          {{ vault_token_string }}
          url={{ vault_url }}')[vault_secret_cert_keyname] }}
        dest: "{{ cert_dest_dir }}/{{ item }}-cert.pem"
        owner: "root"
        group: "root"
        mode: 0644
      loop: "{{ certificates }}"

    - name: Provide TLS private keys from Vault
      copy:
        content: >-
          {{ lookup(
          'hashi_vault',
          'secret={{ vault_path.rstrip("/") }}/{{ item }}
          {{ vault_token_string }}
          url={{ vault_url }}')[vault_secret_key_keyname] }}
        dest: "{{ cert_dest_dir }}/{{ item }}-private-key.pem"
        owner: "root"
        group: "root"
        mode: 0600
      loop: "{{ certificates }}"

    - name: Gather certificate information
      community.crypto.x509_certificate_info:
        path: "{{ cert_dest_dir }}/{{ item }}-cert.pem"
      register: cert_info
      loop: "{{ certificates }}"

    - name: Gather private key information
      community.crypto.openssl_privatekey_info:
        path: "{{ cert_dest_dir }}/{{ item }}-private-key.pem"
      register: pk_info
      loop: "{{ certificates }}"

    - name: Validate certificates
      ansible.builtin.assert:
        that:
          - not item.expired
        quiet: false
        success_msg: "{{ item.subject }} certificate is valid"
        fail_msg: "{{ item.subject }} certificate is NOT valid"
      loop: "{{ cert_info.results}}"

    - name: Validate certificates belong to private keys
      ansible.builtin.assert:
        that:
          - item.0.public_key == item.1.public_key
        quiet: false
        success_msg: "{{ item.0.subject }} key validation success"
        fail_msg: "{{ item.0.subject }} key validation FAIL"
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-together
      loop: "{{ cert_info.results|zip(pk_info.results)|list }}"
